spring:
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5432/postgres}"
    driver-class-name: org.postgresql.Driver
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:1}"
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    user:
      name: admin
      password: 1

